/*----------------------------------------------------------------------------------------------
   Description:     Unit test class for AccountUpdateChildContactAddressHandler
   History:         12-August-2020     Ian Huang     Created
----------------------------------------------------------------------------------------------*/
@isTest
private class AccountUpdateChildContactAddressHdr_Test {
    
    @testSetup static void setupTestData() {
        //create account
        //create contacts
    }
    
    @isTest static void unitTest1() {
        //
    }    

}